#include <stdlib.h>
#include <stdio.h>
#include <stdint.h>
#include <stdbool.h>
#include <libgte.h>
#include <libgpu.h>
#include <inline_c.h>
#include "display.h"
#include "trtypes.h"
#include "const.h"
#include "clip.h"